[tool.poetry]
name = "keepyrs"
version = "0.1.0"
description = ""
authors = ["soundsonacid <soundsonacid@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
driftpy = {path = "/Users/frankfinnegan/Documents/musings/drift/driftpy"}
anchorpy = "0.17.1"
solana = "0.30.1"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
